### ISSUE TITLE
Typo in Welcome Screen

### ISSUE THREAD

**Issue by prakharb5** [M2Team/NanaBox#10] opened 2024-06-10 11:18 UTC
"Configuration File Reference **Documentatio**"

should be => "Documentation"

![image](https://github.com/M2Team/NanaBox/assets/51435948/7df0604f-bb30-4737-b4f5-d854b2a5430f)

**Comment by MouriNaruto** [comment] 2024-06-10 11:26
It looks like the font is too big to be unable to show all string, lol.

I have checked the implementation, have no typos.

I think I will try to fix that if I can reproduce it.

Kenji Mouri

**Comment by MouriNaruto** [comment] 2024-06-10 11:30
https://x.com/MouriNaruto/status/1726097295832383737/photo/1
According to the screenshot I posted on Twitter, and your screenshot, your issue may caused by a lack of fonts.

Kenji Mouri

**Comment by prakharb5** [comment] 2024-06-12 04:36
Hello. Yeah, I have increased text size from accessibility settings to 110%, with display scale at 100%. Most apps are able to accommodate this change, except NanaBox :(

**Comment by MouriNaruto** [comment] 2024-06-12 12:14
The issue should be fixed after the commit https://github.com/M2Team/NanaBox/commit/5e0cfb25cb610d2041816a95a4155c74afa05e3d.

Kenji Mouri

**Comment by prakharb5** [comment] 2024-06-13 04:44
Yeah, the issue is fixed with this _"band-aid"_ change.

But ideally, I think the font size _should_ be the same as rest of the system. This change would up making the text smaller than normal if someone has changed it from accessibility settings. Is it possible for you to look into this further? Although I agree that it would be a very niche thing.

**Comment by MouriNaruto** [comment] 2024-06-14 14:31
Close this issue because your suggestion to redirect to a new issue.
https://github.com/M2Team/NanaBox/issues/15

Kenji Mouri

**Closed as completed by MouriNaruto** 2024-06-14 14:31 UTC
Labels: bug, archived, fixed
